spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
server:
  port: 8888
application:
  version: under dev
  title: ${spring.application.name}